apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      alpha.image.policy.openshift.io/resolve-names: '*'
      app.openshift.io/vcs-ref: ""
      app.openshift.io/vcs-uri: https://github.com/elsony/devfile-sample-java-springboot-basic.git
      deployment.kubernetes.io/revision: "1"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"java-springboot-basic:latest","namespace":"citi-poc"},"fieldPath":"spec.template.spec.containers[?(@.name==\"java-springboot-basic\")].image","pause":"false"}]'
      isFromDevfile: "true"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"alpha.image.policy.openshift.io/resolve-names":"*","app.openshift.io/vcs-ref":"","app.openshift.io/vcs-uri":"https://github.com/elsony/devfile-sample-java-springboot-basic.git","deployment.kubernetes.io/revision":"1","image.openshift.io/triggers":"[{\"from\":{\"kind\":\"ImageStreamTag\",\"name\":\"java-springboot-basic:latest\",\"namespace\":\"citi-poc\"},\"fieldPath\":\"spec.template.spec.containers[?(@.name==\\\"java-springboot-basic\\\")].image\",\"pause\":\"false\"}]","isFromDevfile":"true","openshift.io/generated-by":"OpenShiftWebConsole"},"creationTimestamp":"2022-11-28T18:45:59Z","finalizers":["foregroundDeletion"],"generation":1,"labels":{"app":"java-springboot-basic","app.kubernetes.io/component":"java-springboot-basic","app.kubernetes.io/instance":"java-springboot-basic","app.kubernetes.io/name":"java-springboot-basic","app.kubernetes.io/part-of":"sample-app","app.openshift.io/runtime":"java-springboot-basic"},"name":"java-springboot-basic","namespace":"citi-poc","resourceVersion":"6914679","uid":"95234f18-15bc-482f-b641-f9efe4c01c91"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"java-springboot-basic"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"java-springboot-basic","deploymentconfig":"java-springboot-basic"}},"spec":{"containers":[{"env":[{"name":"PROJECTS_ROOT","value":"/projects"},{"name":"PROJECT_SOURCE","value":"/projects"}],"image":"java-springboot-basic:latest","imagePullPolicy":"Always","name":"java-springboot-basic","ports":[{"containerPort":8081,"name":"8081-tcp","protocol":"TCP"}],"resources":{"limits":{"memory":"1Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"collisionCount":1,"conditions":[{"lastTransitionTime":"2022-11-28T18:45:53Z","lastUpdateTime":"2022-11-28T18:45:53Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"},{"lastTransitionTime":"2022-11-28T18:55:54Z","lastUpdateTime":"2022-11-28T18:55:54Z","message":"ReplicaSet \"java-springboot-basic-9b46987c6\" has timed out progressing.","reason":"ProgressDeadlineExceeded","status":"False","type":"Progressing"}],"observedGeneration":1,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2022-11-28T18:45:59Z"
    finalizers:
    - foregroundDeletion
    generation: 2
    labels:
      app: java-springboot-basic
      app.kubernetes.io/component: java-springboot-basic
      app.kubernetes.io/instance: java-springboot-basic
      app.kubernetes.io/name: java-springboot-basic
      app.kubernetes.io/part-of: sample-app
      app.openshift.io/runtime: java-springboot-basic
    name: java-springboot-basic
    namespace: citi-poc
    resourceVersion: "15361739"
    uid: 95234f18-15bc-482f-b641-f9efe4c01c91
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: java-springboot-basic
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: java-springboot-basic
          deploymentconfig: java-springboot-basic
      spec:
        containers:
        - env:
          - name: PROJECTS_ROOT
            value: /projects
          - name: PROJECT_SOURCE
            value: /projects
          image: java-springboot-basic:latest
          imagePullPolicy: Always
          name: java-springboot-basic
          ports:
          - containerPort: 8081
            name: 8081-tcp
            protocol: TCP
          resources:
            limits:
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    collisionCount: 1
    conditions:
    - lastTransitionTime: "2022-11-28T18:45:53Z"
      lastUpdateTime: "2022-11-28T18:45:53Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2022-11-28T18:55:54Z"
      lastUpdateTime: "2022-11-28T18:55:54Z"
      message: ReplicaSet "java-springboot-basic-9b46987c6" has timed out progressing.
      reason: ProgressDeadlineExceeded
      status: "False"
      type: Progressing
    observedGeneration: 2
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2022-11-28T18:45:59Z","generation":1,"labels":{"app":"spring-music"},"name":"spring-music","namespace":"citi-poc","resourceVersion":"6910987","uid":"9bda5d90-8ed5-4f36-a3db-f8b3d10a7937"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"spring-music"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"spring-music"},"namespace":"default"},"spec":{"containers":[{"image":"harbor.dell.local/library/spring-music@sha256:f20d241710ff5dac3f20bfab6645ff8ab8bbfa7b34832fd1b4582f14d6015dcc","imagePullPolicy":"Always","name":"spring-music","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/tmp","name":"spring-music-1"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"emptyDir":{},"name":"spring-music-1"}]}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2022-11-28T18:46:04Z","lastUpdateTime":"2022-11-28T18:46:04Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2022-11-28T18:45:53Z","lastUpdateTime":"2022-11-28T18:46:04Z","message":"ReplicaSet \"spring-music-5889555c96\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
    creationTimestamp: "2022-11-28T18:45:59Z"
    generation: 2
    labels:
      app: spring-music
    name: spring-music
    namespace: citi-poc
    resourceVersion: "15361743"
    uid: 9bda5d90-8ed5-4f36-a3db-f8b3d10a7937
  spec:
    progressDeadlineSeconds: 600
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: spring-music
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: spring-music
        namespace: default
      spec:
        containers:
        - image: harbor.dell.local/library/spring-music@sha256:f20d241710ff5dac3f20bfab6645ff8ab8bbfa7b34832fd1b4582f14d6015dcc
          imagePullPolicy: Always
          name: spring-music
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp
            name: spring-music-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: spring-music-1
  status:
    availableReplicas: 3
    conditions:
    - lastTransitionTime: "2022-11-28T18:46:04Z"
      lastUpdateTime: "2022-11-28T18:46:04Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-11-28T18:45:53Z"
      lastUpdateTime: "2022-11-28T18:46:04Z"
      message: ReplicaSet "spring-music-5889555c96" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 3
    replicas: 3
    updatedReplicas: 3
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      app.openshift.io/vcs-ref: ""
      app.openshift.io/vcs-uri: https://github.com/elsony/devfile-sample-java-springboot-basic.git
      isFromDevfile: "true"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"app.openshift.io/vcs-ref":"","app.openshift.io/vcs-uri":"https://github.com/elsony/devfile-sample-java-springboot-basic.git","isFromDevfile":"true","openshift.io/generated-by":"OpenShiftWebConsole"},"creationTimestamp":"2022-11-28T18:45:59Z","labels":{"app":"java-springboot-basic","app.kubernetes.io/component":"java-springboot-basic","app.kubernetes.io/instance":"java-springboot-basic","app.kubernetes.io/name":"java-springboot-basic","app.kubernetes.io/part-of":"sample-app","app.openshift.io/runtime":"java-springboot-basic"},"name":"java-springboot-basic","namespace":"citi-poc","resourceVersion":"6910844","uid":"604cb669-f6b6-442d-904c-9bebb09e61bf"},"spec":{"clusterIP":"172.30.88.7","clusterIPs":["172.30.88.7"],"ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"port-8081","port":8081,"protocol":"TCP","targetPort":8081}],"selector":{"app":"java-springboot-basic","deploymentconfig":"java-springboot-basic"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2022-11-28T18:45:59Z"
    labels:
      app: java-springboot-basic
      app.kubernetes.io/component: java-springboot-basic
      app.kubernetes.io/instance: java-springboot-basic
      app.kubernetes.io/name: java-springboot-basic
      app.kubernetes.io/part-of: sample-app
      app.openshift.io/runtime: java-springboot-basic
    name: java-springboot-basic
    namespace: citi-poc
    resourceVersion: "15361744"
    uid: 604cb669-f6b6-442d-904c-9bebb09e61bf
  spec:
    clusterIP: 172.30.88.7
    clusterIPs:
    - 172.30.88.7
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: port-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: java-springboot-basic
      deploymentconfig: java-springboot-basic
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"ncp/internal_ip_for_policy":"100.64.32.9"},"creationTimestamp":"2022-11-28T18:45:59Z","name":"spring-music","namespace":"citi-poc","resourceVersion":"6910955","uid":"0655bcdd-15e9-4cf0-90d9-3227469ee1df"},"spec":{"clusterIP":"172.30.79.59","clusterIPs":["172.30.79.59"],"externalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":30022,"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"spring-music"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{"ingress":[{"ip":"172.16.172.2"}]}}}
      ncp/internal_ip_for_policy: 100.64.32.9
    creationTimestamp: "2022-11-28T18:45:59Z"
    name: spring-music
    namespace: citi-poc
    resourceVersion: "15361747"
    uid: 0655bcdd-15e9-4cf0-90d9-3227469ee1df
  spec:
    clusterIP: 172.30.79.59
    clusterIPs:
    - 172.30.79.59
    externalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30022
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: spring-music
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 172.16.172.2
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"},"creationTimestamp":"2022-11-28T18:46:00Z","labels":{"app":"spring-music-v1","app.kubernetes.io/component":"spring-music-v1","app.kubernetes.io/instance":"spring-music-v1","app.kubernetes.io/name":"spring-music-v1","app.kubernetes.io/part-of":"sample-app","app.openshift.io/runtime-version":"78"},"name":"spring-music-v1","namespace":"citi-poc","resourceVersion":"6910870","uid":"228d8517-a95b-4934-b796-1f65a8f1d69e"},"spec":{"clusterIP":"172.30.186.146","clusterIPs":["172.30.186.146"],"ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"8080-tcp","port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"spring-music-v1","deploymentconfig":"spring-music-v1"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: "2022-11-28T18:46:00Z"
    labels:
      app: spring-music-v1
      app.kubernetes.io/component: spring-music-v1
      app.kubernetes.io/instance: spring-music-v1
      app.kubernetes.io/name: spring-music-v1
      app.kubernetes.io/part-of: sample-app
      app.openshift.io/runtime-version: "78"
    name: spring-music-v1
    namespace: citi-poc
    resourceVersion: "15361748"
    uid: 228d8517-a95b-4934-b796-1f65a8f1d69e
  spec:
    clusterIP: 172.30.186.146
    clusterIPs:
    - 172.30.186.146
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: spring-music-v1
      deploymentconfig: spring-music-v1
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
